#!/usr/bin/env python3
"""Generate protocol-manifest.json from evm/precompiles.go.

Canonical machine-readable source of truth for:
  - precompile count / range / names
  - address-model + selector conventions
  - canonical repo map

CI runs this with --check to fail on drift (issue #23 / #24).
"""
from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SRC = ROOT / "evm" / "precompiles.go"
OUT = ROOT / "protocol-manifest.json"


def parse_precompiles(text: str) -> list[dict]:
    block = re.search(
        r"var PrecompilesTable = map\[byte\]\*Precompile\{(.*?)\n\}",
        text,
        re.S,
    )
    if not block:
        raise SystemExit("PrecompilesTable not found in evm/precompiles.go")
    body = block.group(1)
    entries: list[dict] = []
    for m in re.finditer(r"^\s*0x([0-9A-Fa-f]{2}):\s*\{", body, re.M):
        addr = int(m.group(1), 16)
        sub = body[m.start() : m.start() + 500]
        nm = re.search(r'Name:\s*"([^"]+)"', sub)
        if not nm:
            raise SystemExit(f"Name missing for 0x{addr:02X}")
        entries.append(
            {
                "addr": f"0x{addr:02X}",
                "addr_byte": addr,
                "name": nm.group(1),
            }
        )
    entries.sort(key=lambda e: e["addr_byte"])
    if len(entries) != 27:
        raise SystemExit(f"expected 27 precompiles, found {len(entries)}")
    if entries[0]["addr_byte"] != 0x0C or entries[-1]["addr_byte"] != 0x26:
        raise SystemExit(
            f"range must be 0x0C-0x26, got {entries[0]['addr']}-{entries[-1]['addr']}"
        )
    # contiguity check — no holes in 0x0C..0x26
    expected = list(range(0x0C, 0x27))
    got = [e["addr_byte"] for e in entries]
    if got != expected:
        raise SystemExit(f"precompile address set not contiguous 0x0C-0x26: {got}")
    return entries


def build_manifest(entries: list[dict]) -> dict:
    return {
        "schema_version": 1,
        "protocol": "WayChain",
        "chain_id": 10008,
        "chain_id_hex": "0x2718",
        "precompile_count": len(entries),
        "precompile_range": {"start": "0x0C", "end": "0x26"},
        "hash_selectors": "sha256(signature)[:4]",
        "eoa_account_key": "full 64-hex ed25519 pubkey",
        "eoa_display_address": "20-byte pub[0:40]",
        "precompile_calldata_address": "raw 20-byte",
        "canonical_repos": {
            "protocol": "ThinkIbrokeIt/waychain-consensus",
            "site": "ThinkIbrokeIt/waychain-site",
            "mobile": "ThinkIbrokeIt/waychain-mobile",
            "client_releases": "ThinkIbrokeIt/waychain-client",
            "contracts_legacy": "ThinkIbrokeIt/waychain-contracts",
            "live_node": "AWS 3.89.116.45 waychain.service /usr/local/bin/waychain",
        },
        "precompiles": [{"addr": e["addr"], "name": e["name"]} for e in entries],
        "notes": [
            "Generated by scripts/gen-protocol-manifest.py from evm/precompiles.go.",
            "CI --check fails if this file drifts from generation.",
            "AWS live binary hash is operational SoT for 'deployed' (see issue #27).",
            "0x21 is WIFRGantletRewards — NOT Keccak256.",
        ],
    }


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument(
        "--check",
        action="store_true",
        help="exit non-zero if protocol-manifest.json does not match generation",
    )
    args = ap.parse_args()
    text = SRC.read_text()
    manifest = build_manifest(parse_precompiles(text))
    rendered = json.dumps(manifest, indent=2) + "\n"

    if args.check:
        if not OUT.exists():
            print(f"::error::{OUT.name} missing — run scripts/gen-protocol-manifest.py")
            return 1
        current = OUT.read_text()
        if current != rendered:
            print(f"::error::{OUT.name} drift vs evm/precompiles.go")
            print("Re-run: python3 scripts/gen-protocol-manifest.py")
            return 1
        print(f"✅ {OUT.name} matches PrecompilesTable ({manifest['precompile_count']})")
        return 0

    OUT.write_text(rendered)
    print(f"wrote {OUT} ({manifest['precompile_count']} precompiles)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
